app/library/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic import TemplateView

from .views import StreamListView, StreamViewDetailView, StreamSearchListView

urlpatterns = [
    url(r'search/', StreamSearchListView.as_view(), name='search'),
    url(r'cat/(?P<category>\w+)/', StreamListView.as_view(), name='stream_cat'),
    url(r'stream/view/(?P<stream_id>\d+)/', StreamViewDetailView.as_view(), name='stream_view'),
]

app/mystream/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from library.views import upload_file
from library.views import StreamListView

urlpatterns = [
    url(r'^admin/library/stream/add/', upload_file, name='uploadform'),
    url(r'^admin/library/stream/encoding_process', TemplateView.as_view(template_name='encoding_process.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^library/$', StreamListView.as_view(), name='index'),
    url(r'^library/', include('library.urls', namespace='library')),
]

app/library/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Quality(models.Model):
    
    name = models.CharField(max_length=15)
    cmd = models.CharField(max_length=255)
    directory = models.CharField(max_length=20)

    def __str__(self):
        return self.name

LANGUAGE_CHOICE = (
    ('VF', 'VF'),
    ('VOSTFR', 'VOSTFR'),
    ('VO', 'VO'),
)

class Stream(models.Model):
    
    name = models.CharField(
                max_length=60,
            )

    description = models.TextField()
    
    quality = models.ManyToManyField(Quality)

    movie = models.CharField(
                max_length=255,
                null=True,
            )

    encoded = models.BooleanField(default=0)
    
    date = models.DateTimeField(auto_now=True)

    language = models.CharField(
                max_length=10, 
                choices=LANGUAGE_CHOICE, 
                default='VOSTFR',
            )

    category = models.ForeignKey(Category)

    def __str__(self):
        return self.name

class StreamTmp(models.Model):

    tmppath = models.CharField(
                max_length=255,
            )

    stream = models.ForeignKey(Stream)

app/library/forms.py
#!/usr/bin/python

from django import forms

from .models import Category, Quality
from .models import LANGUAGE_CHOICE

class StreamForm(forms.Form):

    stream_name = forms.CharField(label='Name', max_length=100)
    stream_description = forms.CharField(label='Description', widget=forms.Textarea)
    stream_quality = forms.ModelMultipleChoiceField(
                                queryset=Quality.objects.all(),
                                widget=forms.CheckboxSelectMultiple,
                        )
    stream_language =  forms.ChoiceField(choices=LANGUAGE_CHOICE)
    stream_category = forms.ModelChoiceField(queryset=Category.objects.all())

app/library/views.py
from pprint import pprint

import operator

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.shortcuts import Http404
from django.db.models.functions import Lower
from celery import chord


from .models import Stream, StreamTmp, Category, Quality
from .forms import StreamForm
from .tasks import encode_stream, post_encoding
from .extras.savefile import SaveStream

# MY OWN VIEW HERE

@login_required(login_url='/admin/login/')
@csrf_exempt
def upload_file(request):
    """
    View form to override the admin admin/add/stream/
    """

    if request.method == 'POST':
        form = StreamForm(request.POST)

        if form.is_valid() and request.FILES:
            stream_file = request.FILES['stream_file']
            fs = SaveStream()
            tmpfilename = fs.save(stream_file.name, stream_file)

            # Save streaming file info
            stream_name = form.cleaned_data['stream_name']
            stream_description = form.cleaned_data['stream_description']
            stream_quality = form.cleaned_data['stream_quality']
            stream_language = form.cleaned_data['stream_language']
            stream_category = form.cleaned_data['stream_category']

            cat = Category.objects.get(name=stream_category)

            stream = Stream(
                name=stream_name,
                description=stream_description,
            )

            stream.category = cat
            stream.save()

            # stream_quality is a list of QuerySet
            # We make the many-to-many relation
            stream.quality = stream_quality

            # Save streaming tmp file info
            StreamTmp(
                tmppath=tmpfilename,
                stream=stream,
            ).save() 

            # Run encoding process in celery tasks with chord primitive
            chord(encode_stream.si(tmpfilename, qual.name) 
                        for qual in stream_quality)(post_encoding.si(tmpfilename))


            return HttpResponseRedirect('/admin/library/stream/encoding_process/')

    else:
        form = StreamForm()

    return render(request, 'upload.html', {'form': form})


class StreamListView(ListView):
    """
    List all streams or by category
    """

    template_name = 'stream_list.html'
    context_object_name = "streams"

    def get_context_data(self, *args, **kwargs):
        context = super(StreamListView, self).get_context_data(*args, **kwargs)
        cat = self.kwargs.get('category', 'None')

        # If cat is equal None, we list all object
        if cat != 'None':
            try:
                category = Category.objects.get(name = cat)
            except Category.DoesNotExist:
                raise Http404

        return context
        

    def get_queryset(self):
        cat = self.kwargs.get('category', 'None')

        if cat == 'None':
            return Stream.objects.filter(encoded=1).order_by(Lower('name'))
        else:
            return Stream.objects.filter(encoded=1, category__name=cat).order_by(Lower('name'))


class StreamSearchListView(ListView):
    """
    List result of the search request
    """

    template_name = 'stream_list.html'
    context_object_name = "streams"

    def get_queryset(self):
        result = Stream.objects.filter(encoded=1)

        query = self.request.GET.get('q')

        if query:
            query_list = query.split()

            result = result.filter(
                reduce(operator.and_,
                       (Q(name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list))
            ).order_by(Lower('name'))

            return result



class StreamViewDetailView(DetailView):
    """
    Print page with video
    """

    template_name = 'stream_viewer.html'
    context_objects_name = 'stream'

    def get_context_data(self, **kwargs):
        context = super(StreamViewDetailView, self).get_context_data(**kwargs)
        context['base_path'] = settings.MEDIA_URL

        query = self.request.GET.get('q')

        if query:
            try:
                quality_dir = Quality.objects.get(name=query)
                context['directory'] = quality_dir.directory
            except Quality.DoesNotExist:
                raise Http404

        try:
            qual = Stream.objects.filter(id=self.kwargs['stream_id'], quality__in=Quality.objects.all())
            context['quality'] = qual[0].quality.all()
        except Stream.DoesNotExist:
            raise Http404

        return context

    def get_object(self):
        try:
            return Stream.objects.get(id=self.kwargs['stream_id'])
        except Stream.DoesNotExist:
            raise Http404

app/library/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <link href="{% static "jquery-ui-1.12.1/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "jquery-ui-1.12.1/jquery-ui.structure.min.css" %}" rel="stylesheet">

    <style>
       nav {
            box-shadow: 0px 5px 5px #656565;
        } 
    </style>
    {% block extrat_style %}{% endblock %}

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% include "nav.html" %}

    <div id='content' style='margin-top:80px; margin-left: 20px'>
    {% block content %}{% endblock %} 
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "jquery-ui-1.12.1/jquery-ui.min.js" %}"></script>
    {% block extra_script %}{% endblock %}
  </body>
</html>

app/library/templates/encoding_process.html
{% extends "admin/base_site.html" %}

{% block extrahead %}
<meta http-equiv="refresh" content="2; url=/admin/library/stream/">
{% endblock %}

{% block content %}
<h1>The encoding process will start...</h1>
{% endblock %}

app/library/templates/nav.html
{% load static %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'index' %}"><img alt="" src="{% static "img/logo.png" %}"/></a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" method="get" action="{% url 'library:search' %}">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name="q" id="q">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
          <ul class="dropdown-menu">
             {% load category %}{% show_category 'nav' %}{{ res }}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/library/templates/stream_list.html
{% extends "base.html" %}

{% block title %}Streams{% endblock %}

{% block extrat_style %}
<style>
    h1 {
        border-bottom: 1px solid #dedede;
    }

    .info {
        padding-top: 10px;
        height: 40px;
        width: 80px;
        border: 1px solid #091529;
        border-radius: 10px;
        text-align: center;
    }

    .syn {
        text-decoration: underline;
        padding-bottom: 5px;
    }

    .desc {
        font-style: italic;
        padding-bottom: 8px;
        
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8"><h1>My Streams</h1>
            <div id="accordion">
                {% for stream in streams %}
                <h3>{{ stream.name }}</h3>
                <div class="row stream">
                      <div class="col-xs-12 syn">Synopsis:</div>
                      <div class="col-xs-12 desc">{{ stream.description }}</div>
                      <div class="col-xs-offset-1 col-xs-2 info">{{ stream.category | title }}</div>
                      <div class="col-xs-offset-1 col-xs-2 info">{{ stream.language }}</div>
                      <div class="col-xs-offset-4 col-xs-2"><a href="{% url 'library:stream_view' stream.id %}">{% load static %}<img src="{% static 'img/click.png' %}"/></a></div>
                </div>
                {% endfor %}
            </div>
        <div class="col-lg-offset-1 col-lg-2"><!-- Futur Block --!></div>
    </div>
</div>

{% endblock %}

{% block extra_script %}
<script>
    $( "#accordion" ).accordion({
        collapsible: true,
        animate: 600,
        active: false
    });
</script>
{% endblock %}

app/library/templates/stream_viewer.html
{% extends "base.html" %}
{% block title %}Stream {{ stream.name }}{% endblock %}
{% block content %}

<div class="container container-table">
  <div class="row vertical-center-row">
    <div class="col-md-3 col-md-offset-3">
      <h3>{{ stream.name }}</h3>
    </div>
  </div>

  <div class="row vertical-center-row">
    <div class="col-md-3 col-md-offset-3">
      <span>Quality :</span>
       {% for qual in quality %}
       <a role="button" class="btn btn-warning" href="{% url 'library:stream_view' stream.id %}?q={{ qual.name }}">{{ qual.name }}</a>
       {% endfor %}
    </div>
  </div>

  <div class="row vertical-center-row" style="padding-top:5px">
    <div class="col-md-3 col-md-offset-3">
      <video controls>
        {% if quality|length_is:"1" %}
          <source src="{{ base_path }}{% for q in quality %}{{ q.directory }}{% endfor %}{{ stream.movie }}" type="video/mp4">
        {% else %}
          <source src="{{ base_path }}{{ directory | default:'low/' }}{{ stream.movie }}" type="video/mp4">
        {% endif %}
      </video>
    </div>
  </div>
</div>

<style>
    /* Additional style */
    video {
        width: 700px;
    }

    @media only screen and (max-width: 640px){
        video {
            width: 300px;
            height: 250px;
        }
    }
</style>
{% endblock %}

app/library/templates/upload.html
{% extends "admin/base_site.html" %}

{% load static %}
{% block extrastyle %}
    <link href="{% static "jquery-ui-1.12.1/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "jquery-ui-1.12.1/jquery-ui.structure.min.css" %}" rel="stylesheet">

<style type="text/css">
    #spinner {
        position:absolute;
        top:40%;
        left:45%;
        z-index:3;
        display:none;
    }

    #overlay {
        position:absolute;
        height:100%;
        width:100%;
        background:black;
        opacity:.7;
        z-index:2;
        display:none;
    }
    
</style>
{% endblock %}

{% block content %}

<div id="dialog"></div>
<div id="overlay"></div>
<div id="spinner">
    <img id="img-spinner" src="{% static "img/uploading.gif" %}" alt="Loading"/>
</div>

<!-- Necessary enctype to upload file --!>
<form enctype="multipart/form-data" method="post" id="formup">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="file" name="stream_file"><br /><br />
    <input type="submit" value="Submit" id="button-upload" />
</form>
{% endblock %}

{% block footer %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static "jquery-ui-1.12.1/jquery-ui.min.js" %}"></script>

<script>

$("#button-upload").click( function (event) {

    // Do not prevent default event (Here submitting!)
    event.preventDefault();

    var formData = new FormData($("#formup").get(0));
    
    $.ajax({
            url : '{% url 'uploadform' %}',
            type : 'POST',
            data : formData,
            processData: false,  // tell jQuery not to process the data
            contentType: false,  // tell jQuery not to set contentType

            beforeSend: function(data) {
                $("#spinner").show();
                $("#overlay").show();
            },

            success : function(data) {
                var dial = $("<div></div>").dialog({
                     title: "Wait",
                     modal: true,
                     width: 700,
                     height: 500,
                     resizable: false,
                });

                dial.dialog('open');
                dial.html(data);
            },

            error: function(data) {
                var dial = $("<div></div>").dialog({
                     title: "Error",
                     modal: true,
                     width: 700,
                     height: 500,
                     resizable: false,
                });

                dial.dialog('open');
                dial.html("<h3>An error Occured</h3>");
                window.location.replace("{% url 'uploadform' %}");
            },

    });

});

</script>
{% endblock %}